; ============================================================
; PlatformIO – ESP32WoMo
; Board: Sunton ESP32-S3 4.3" 800x480
; ============================================================

[platformio]
default_envs = esp32-8048S043C
boards_dir   = boards

[env]
platform  = espressif32
framework = arduino

monitor_speed   = 115200
monitor_rts     = 0
monitor_dtr     = 0
monitor_filters = esp32_exception_decoder

upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0

board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi

build_flags =
    -Ofast
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER

lib_deps =
    ; Display + LVGL
    https://github.com/rzeldent/esp32-smartdisplay.git

    ; Webserver (bewährte Kombination für ESP32-S3 / Core 3.x)
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ayushsharma82/ElegantOTA.git

    ; Datenformate
    bblanchon/ArduinoJson @ ^7

    ; Bluetooth vom Victron
    ; https://gitea.sh3d.com.au/Sh3d/VictronBLE geht nicht, daher direkt in das lib verzeichnis gepackt
    ; SD-Karte (ist im ESP32-Arduino-Framework enthalten,
    ; explizit angeben damit die Version klar ist)
    ; SD wird über SPI angesprochen – keine extra lib nötig

[env:esp32-8048S043C]
board = esp32-8048S043C

[env:esp32-8048S043R]
board = esp32-8048S043R

[env:esp32-8048S043N]
board = esp32-8048S043N