[platformio]
default_envs = lolin_s2_mini

[env:lolin_s2_mini]
platform  = espressif32
board     = lolin_s2_mini
framework = arduino
monitor_speed = 115200


lib_deps =
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ayushsharma82/ElegantOTA.git
    bblanchon/ArduinoJson @ ^7
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14