
[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_unflags =
    -DARDUINO_USB_MODE
build_flags =
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_rts = 0
monitor_dtr = 0

lib_deps =
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ayushsharma82/ElegantOTA.git
    bblanchon/ArduinoJson @ ^7
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    sensirion/Sensirion I2C SCD4x

; der ältere s2 mini

[env:lolin_s2_mini]
platform  = espressif32
board     = lolin_s2_mini
framework = arduino
monitor_speed = 115200


build_flags =
    -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER
board_build.filesystem = littlefs

lib_deps =
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ayushsharma82/ElegantOTA.git
    bblanchon/ArduinoJson @ ^7
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14

